name: LibsHungergames
main: me.libraryaddict.Hungergames.Hungergames
author: libraryaddict
version: 0.6
website: http://dev.bukkit.org/server-mods/hunger-games/
load: startup
softdepend: [LibsCommands, DisguiseCraft, Vault]
commands:
  time:
  players:
  fstart:
  build:
  goto:
  kit:
  kitinfo:
  kititems:
  track:
  feast:
  chunk:
    aliases: [stuck]
  kill:
  suicide:
  invis:
  ride:
  creator:
    aliases: [download]
  buykit: