name: LibsHungergames
main: me.libraryaddict.Hungergames.Hungergames
author: libraryaddict
version: 1.5.2
website: http://dev.bukkit.org/server-mods/hunger-games/
load: startup
softdepend: [LibsCommands, iDisguise, Vault]
commands:
  time:
  players:
  forcestart:
    aliases: [fstart]
  forcetime:
    aliases: [ftime]
  build:
  goto:
  kit:
    aliases: [kits]
  kitinfo:
  kititems:
  track:
  feast:
  chunk:
    aliases: [stuck]
  kill:
  suicide:
  invis:
  ride:
  creator:
    aliases: [download]
  buykit:
  forcefeast:
    aliases: [ffeast]